apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ template "kube-ingress-aws-controller.fullname" . }}
  labels:
    app: {{ template "kube-ingress-aws-controller.name" . }}
    chart: {{ template "kube-ingress-aws-controller.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "kube-ingress-aws-controller.name" . }}
      release: {{ .Release.Name }}
      component: ingress
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ template "kube-ingress-aws-controller.fullname" . }}
      labels:
        app: {{ template "kube-ingress-aws-controller.name" . }}
        release: {{ .Release.Name }}
        component: ingress
    spec:
      serviceAccountName: {{ template "kube-ingress-aws-controller.serviceAccountName" . }}
      hostNetwork: true
      containers:
      - name: {{ template "kube-ingress-aws-controller.name" . }}
        image: "{{ .Values.daemonset.image.repository }}:{{ .Values.daemonset.image.tag }}"
        imagePullPolicy: "{{ .Values.daemonset.image.pullPolicy }}"
        ports:
        - name: ingress-port
          containerPort: {{ .Values.daemonset.port }}
          hostPort: {{ .Values.daemonset.port }}
        args:
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-in-cluster"
          - "-address=:{{ .Values.daemonset.port }}"
          - "-proxy-preserve-host"
          - "-serve-host-metrics"
          - "-enable-ratelimits"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-kubernetes-https-redirect=true"
          - "-lb-healthcheck-interval=3s"
          - "-metrics-flavour=codahale,prometheus"
          - "-enable-connection-metrics"
        resources:
{{ toYaml .Values.daemonset.resources | indent 12 }}
        readinessProbe:
          httpGet:
            path: /kube-system/healthz
            port: 9999
          initialDelaySeconds: 5
          timeoutSeconds: 5
