apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kube-ingress-aws-controller.name" . }}
  labels:
    app: {{ template "kube-ingress-aws-controller.name" . }}
    chart: {{ template "kube-ingress-aws-controller.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kube-ingress-aws-controller.name" . }}
      release: {{ .Release.Name }}
      component: ingress
  template:
    metadata:
      labels:
        app: {{ template "kube-ingress-aws-controller.name" . }}
        release: {{ .Release.Name }}
        component: ingress
{{- if .Values.controller.annotations }}
      annotations:
{{ toYaml .Values.controller.annotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "kube-ingress-aws-controller.serviceAccountName" . }}
      containers:
      - name: {{ template "kube-ingress-aws-controller.name" . }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
        env:
        - name: AWS_REGION
          value: {{ .Values.controller.awsRegion }}
        resources:
{{ toYaml .Values.controller.resources | indent 10 }}
    {{- with .Values.controller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.controller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
